---
output: html_document
---

```{r}
monthly_income_expense <- reportable_transactions %>%
  group_by(Month, Type) %>%
  summarize(Amount = sum(Amount)) %>%
  mutate(Amount = if_else(Type == "Expense", -Amount, Amount)) %>%
  pivot_wider(names_from = Type, values_from = Amount) %>%
  mutate(`Net` = Income - Expense)

spending_by_type <- reportable_transactions %>%
  group_by(Month, Group) %>%
  summarize(Amount = sum(Amount)) %>%
  pivot_wider(names_from = Group, values_from = Amount) %>%
  mutate(Net = Income + Bills + Discretionary)
```

## Row or Column Break

### Income
```{r}
# current month income valuebox
valueBox(
  monthly_income_expense %>%
    filter(Month == format.Date(Sys.Date(), "%Y-%m")) %>%
    pull(Income) %>%
    dollar(),
  icon = "fa-dollar-sign"
)
```

### Expenses
```{r}
# current month expense valuebox
valueBox(
  monthly_income_expense %>%
    filter(Month == format.Date(Sys.Date(), "%Y-%m")) %>%
    pull(Expense) %>%
    dollar(),
  icon = "fa-dollar-sign"
)
```

### Bill Spending
```{r}
valueBox(
  spending_by_type %>%
    filter(Month == format.Date(Sys.Date(), "%Y-%m")) %>%
    pull(Bills) %>%
    dollar(),
  icon = "fa-dollar-sign"
)
```


### Discretionary Spending
```{r}
valueBox(
  spending_by_type %>%
    filter(Month == format.Date(Sys.Date(), "%Y-%m")) %>%
    pull(Discretionary) %>%
    dollar(),
  icon = "fa-dollar-sign"
)
```

## Row or Column Break

### Income vs Expense
```{r}
# Expenses and Income vs Month Bar Chart

evp_bar_chart <- geom_col(
      data = monthly_income_expense %>%
        select(-Net) %>%
        pivot_longer(-Month, names_to = "Type", values_to = "Amount"),
      mapping = aes(x = Month, y = Amount, fill = Type),
      position = "dodge"
    )

net_line_chart <- geom_line(
    data =  spending_by_type %>% select(Net),
    mapping = aes(x = Month, y = Net, group = 1)
  ) 

net_scatter_chart <-   geom_point(
    data =  spending_by_type %>% select(Net),
    mapping = aes(x = Month, y = Net)
  ) 
  
ggplotly(
   ggplot() + evp_bar_chart + net_line_chart + net_scatter_chart + report_theme
)
```

## Row or Column Break

### Discretionary and Bill Spending

```{r}
ggplotly(
  spending_by_type %>%
    select(-c(Income, Net)) %>%
    mutate(
      Bills = -Bills,
      Discretionary = -Discretionary
    ) %>%
    pivot_longer(-Month, names_to = "Type", values_to = "Amount") %>%
    # plotting
    ggplot(.) + 
    aes(x = Month, y = Amount, group = Type, color = Type) +
    geom_line() +
    geom_point() +
    report_theme + 
    expand_limits(y=0)
)
```